# Status Getters
def get_arm() -> int: ...
def get_abort() -> int: ...
def get_qdm() -> int: ...
def get_launch() -> int: ...
def get_stabilize() -> int: ...

# Status Setters
def set_arm(val: int) -> bool: ...
def set_abort(val: int) -> bool: ...
def set_qdm(val: int) -> bool: ...
def set_launch(val: int) -> bool: ...
def set_stabilize(val: int) -> bool: ...
