# Status Getters
def get_arm() -> int: ...
def get_abort() -> int: ...
def get_qdm() -> int: ...
def get_launch() -> int: ...
def get_stabilize() -> int: ...

# Status Setters
def set_arm(val: int) -> bool: ...
def set_abort(val: int) -> bool: ...
def set_qdm(val: int) -> bool: ...
def set_launch(val: int) -> bool: ...
def set_stabilize(val: int) -> bool: ...

# Data Getters
def get_altitude() -> float: ...
def get_latitude() -> float: ...
def get_longitude() -> float: ...
def get_temperature() -> float: ...
def get_gyro_x() -> float: ...
def get_gyro_y() -> float: ...
def get_gyro_z() -> float: ...
def get_acceleration_x() -> float: ...
def get_acceleration_y() -> float: ...
def get_acceleration_z() -> float: ...
